parameters:
#    trsteel_extra.example.class: Trsteel\ExtraBundle\Example

services:
#    trsteel_extra.example:
#        class: %trsteel_extra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
